import type { Database } from '@/integrations/supabase/types';

/**
 * Single source of truth: the DB enum. Regenerated by Supabase whenever the
 * enum changes, so app-level code can never drift from the schema.
 */
export type EventType = Database['public']['Enums']['event_type'];

/**
 * Row shape as returned by PostgREST. Derived directly from generated types
 * so any column added/removed via migration surfaces as a TS error.
 */
export type PaintballEvent = Database['public']['Tables']['events']['Row'];
export type PaintballEventInsert = Database['public']['Tables']['events']['Insert'];
export type PaintballEventUpdate = Database['public']['Tables']['events']['Update'];

export const EVENT_TYPE_LABELS: Record<EventType, string> = {
  walk_on: 'Walk-On',
  big_game: 'Big Game',
  competition: 'Competition',
  tournament: 'Tournament',
  speedball: 'Speedball',
  scenario: 'Scenario',
  mag_fed: 'Mag-Fed',
  other: 'Other',
};

export const EVENT_TYPE_COLORS: Record<EventType, string> = {
  walk_on: 'event-badge-walk-on',
  big_game: 'event-badge-big-game',
  competition: 'event-badge-competition',
  tournament: 'event-badge-tournament',
  speedball: 'event-badge-speedball',
  scenario: 'event-badge-scenario',
  mag_fed: 'event-badge-mag-fed',
  other: 'event-badge-other',
};
